config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/import'
	root to: "users#index"
	
	get 'users/index'
	
	get 'users/import' => 'users#my_import'
	
	resources :users do
		collection {post :import}
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	require 'csv'
	require 'activerecord-import/base'
	require 'activerecord-import/active_record/adapters/postgresql_adapter'
	def self.my_import(file)
		users = []
		if file
			CSV.foreach(file.path, headers: true) do |row|
				user = row.to_h
				begin
					oldUser = User.find(user['id'])
					User.delete(oldUser['id'])
					user['points'] = (user['points'].to_d + oldUser['points'].to_d)
					user['points'] = [user['points'],3126].min
					users << User.new(user)
				rescue ActiveRecord::RecordNotFound
					user['points'] = [user['points'].to_d,3126].min
					users << User.new(user)
				end
			end
			User.import users, recursive: true
		end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users = User.all
  end

  def import
	User.my_import(params[:file])
	redirect_to root_url, notice: "Successfully Imported Data!!!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DitoChall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/import.html.erb
<h1>Users#import</h1>
<p>Find me in app/views/users/import.html.erb</p>

app/views/users/index.html.erb
<div>
	<h4>Faça upload de um arquivo .csv!</h4>
	<p>A primeira linha do arquivo deve ser: "name,date,id,points"</p>
  <%= form_tag import_users_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Carregar dados na tabela" %>
  <% end %>
</div>
<table id="users-table" class="display">
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>date</th>
      <th>pontos</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.date %></td>
        <td><%= user.points %></td>
      </tr>
    <% end %>
  </tbody>
</table>